apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: popclick

images:
  - name: app
    newName: asia-southeast1-docker.pkg.dev/popclick-485102/popclick-server/popclick-server
    newTag: latest

configMapGenerator:
  - name: app-env
    envs:
      - app.env

secretGenerator:
  - name: app-secret
    envs:
      - app.env

generatorOptions:
  disableNameSuffixHash: false
